# Generated by Django 3.2 on 2021-04-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210415_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='CreationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='DueDate',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='usertasks',
            old_name='ID',
            new_name='id',
        ),
    ]
