# Generated by Django 3.2 on 2021-04-16 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_auto_20210415_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTasks',
            new_name='TaskUser',
        ),
        migrations.CreateModel(
            name='VoiceNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voice_memo', models.FileField(upload_to='recordings')),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasks.task')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
