# Generated by Django 3.2 on 2021-04-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskuser',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(to='tasks.TaskUser'),
        ),
    ]
