# Generated by Django 3.2 on 2021-04-16 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0010_auto_20210416_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='task',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
