# Generated by Django 3.2 on 2021-04-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20210416_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='users',
            new_name='user',
        ),
    ]
